name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: "7.2"
    - uses: php-actions/phpunit@v3
      with:
        php_version: "7.2"
        version: "8"
        args: "tests"
